### PR TITLE
Feature: Neighbouring plots protect from attack.

### PR DESCRIPTION
**Pull request by LlmDl**
#### Brief Description:

Adds 2 new config options, one which enables the feature and another
which sets how many neighbouring plots are required to protect a plot.

This feature is similar to the attack edge plots only, but further slows
attackers by requiring that they attack from a corner and chip away at a
town in order to get to their homeblock.
____
#### Changes:

The feature is off by default, but when it is enabled it will require 3
neighbouring plots to grant protection.

____
#### Relevant FlagWar Issue tickets:

Closes https://github.com/TownyAdvanced/FlagWar/issues/74.
____
- [x] I have tested this pull request for defects on a server.

---
By making this pull request, I represent that I have read and agree to release my own changes that I
have submitted under the terms of the accompanying license (Apache-2.0). I guarantee that these
changes are mine and are not encumbered by any other license or restriction to the best of my
knowledge.

### CODE REVIEW

**Review by TheFlagCourier — COMMENTED** [review]
Looks good, but will need to do some basic testing before merge. I should have some time tomorrow to spin up a test server.

**Comment by LlmDl** [comment]
I can also build it and have @BunkerSlav test it out.

**Comment by TheFlagCourier** [comment]
Either way is fine by me.

**Comment by LlmDl** [comment]
Bunker let me know they're away and unable to test for a while.

**Comment by LlmDl** [comment]
This has been tested with great success.

**Pull request merged**
